### ISSUE TITLE
Error: Error creating Network, ....default already exists

### ISSUE THREAD

**Issue by thapakazi** [abevoelker/Kubernetes-on-Rails-Starter-Files#2]
Following you up on the video you created to create sql with private ip:  
https://github.com/abevoelker/Kubernetes-on-Rails-Starter-Files/blob/f7d5e1f7df33bf1bd72b444daff941d24f554345/stepped-solutions/B1/captioned_images/provision/sql.tf#L45-L53

 I stumbled upon these errors:

```
(master)⚡ % terraform apply  /tmp/plan                                                                      ~/repos/thapakazi/node-3tier-app/provision/gcloud
google_compute_network.vpc_default: Creating...
google_project_service.servicenetworking: Creating...
google_project_service.servicenetworking: Still creating... [10s elapsed]
google_project_service.servicenetworking: Still creating... [20s elapsed]
google_project_service.servicenetworking: Creation complete after 21s [id=terraforming-250207/servicenetworking.googleapis.com]

Error: Error creating Network: googleapi: Error 409: The resource 'projects/terraforming-250207/regions/us-central1/subnetworks/default' already exists, alread
yExists

  on network.tf line 2, in resource "google_compute_network" "vpc_default":
   2: resource "google_compute_network" "vpc_default" {
```

Help needed understand this.... thanks

**Comment by abevoelker** [comment]
It's been awhile but try this:

```
terraform import google_compute_network.vpc_default default
```

Since the network already exists you should be able to import it into Terraform's local state this way

**Comment by thapakazi** [comment]
Thanks for the reply, I followed up from the tutorials and got it working.

Seems there is a default vpc created from the beginning by default.

**Comment by abevoelker** [comment]
Ah yes, my apologies for not making that clearer. When I worked on creating the tutorial I did try to define a brand-new network resource instead of re-using the existing default one, but I wasn't able to get that to work properly. Unfortunately that makes this part of the Terraforming a bit complicated.

Thanks for your patronage and hope the rest of the tutorial goes/went smoother! :tada:
